# Generated by Django 6.0.2 on 2026-04-08 15:27

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_user_agent_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=25, unique=True),
        ),
    ]
