"""
Django settings for Hotel_Booking project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import warnings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(env_path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        # Always apply project .env values so stale shell variables don't override app config.
        os.environ[key] = value


_load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o5^=m1y01xl^t(m3qo&x8%-53sl+n=^ii$wkkis$=w#*6r-#2x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Custom user app MUST be before django.contrib.auth
    'userauths',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Custom apps
    'hotel',
    'user_dashboard.apps.UserDashboardConfig',
    'addon',

    # Third-party apps
    'import_export',
    'crispy_forms',
    'taggit',
    'mathfilters',
    'anymail',
    'ckeditor',
    'ckeditor_uploader',
]
AUTH_USER_MODEL = "userauths.User"

AUTHENTICATION_BACKENDS = [
    'userauths.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Hotel_Booking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Hotel_Booking.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# This is where you keep your project-level static files (development)
STATICFILES_DIRS = [BASE_DIR / 'static']

# This is where collectstatic will collect files (production)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor uploads
CKEDITOR_UPLOAD_PATH = "uploads/"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LOGIN_URL = 'userauths:login'
LOGOUT_URL = 'userauths:logout'
LOGIN_REDIRECT_URL = 'hotel:index'
LOGOUT_REDIRECT_URL = 'hotel:index'

BREVO_SMTP_LOGIN = os.getenv('BREVO_SMTP_LOGIN', '').strip()
BREVO_SMTP_KEY = os.getenv('BREVO_SMTP_KEY', '').strip()
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '').strip()
if not BREVO_API_KEY:
    BREVO_API_KEY = os.getenv('SENDINBLUE_API_KEY', '').strip()
if not BREVO_API_KEY:
    BREVO_API_KEY = os.getenv('BREVO_KEY', '').strip()

# Khalti ePayment configuration
KHALTI_MODE = os.getenv('KHALTI_MODE', 'test').strip().lower()
KHALTI_PUBLIC_KEY = os.getenv('KHALTI_PUBLIC_KEY', '0fbc57ceaf664c3baa5cf67816e4a4d1').strip()
KHALTI_SECRET_KEY = os.getenv('KHALTI_SECRET_KEY', '2185aa6fc925483ebd22bffdc61e4f12').strip()

if KHALTI_MODE == 'test':
    _khalti_default_base = 'https://dev.khalti.com'
else:
    _khalti_default_base = 'https://khalti.com'

KHALTI_INITIATE_URL = os.getenv('KHALTI_INITIATE_URL', f'{_khalti_default_base}/api/v2/epayment/initiate/').strip()
KHALTI_LOOKUP_URL = os.getenv('KHALTI_LOOKUP_URL', f'{_khalti_default_base}/api/v2/epayment/lookup/').strip()


def _to_bool(value, default=False):
    if value is None:
        return default
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


def _to_int(value, default=0):
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return default


# Email (SMTP) configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
_email_provider_env = os.getenv('EMAIL_PROVIDER', '').strip().lower()
_smtp_host_hint = os.getenv('SMTP_HOST', '').strip().lower()
_smtp_login_hint = os.getenv('SMTP_LOGIN', '').strip().lower()
_gmail_user_hint = os.getenv('GMAIL_USER', '').strip().lower() or os.getenv('GMAIL_EMAIL', '').strip().lower()
_gmail_password_hint = os.getenv('GMAIL_APP_PASSWORD', '').strip() or os.getenv('GMAIL_PASSWORD', '').strip()
if _email_provider_env:
    EMAIL_PROVIDER = _email_provider_env
elif _gmail_user_hint or _gmail_password_hint:
    EMAIL_PROVIDER = 'gmail'
elif BREVO_SMTP_LOGIN or BREVO_SMTP_KEY or 'brevo' in _smtp_host_hint or 'smtp-brevo.com' in _smtp_login_hint:
    EMAIL_PROVIDER = 'brevo'
else:
    EMAIL_PROVIDER = 'gmail'

_EMAIL_PROVIDER_DEFAULTS = {
    'gmail': {
        'host': 'smtp.gmail.com',
        'port': 587,
        'tls': True,
    },
    'sendgrid': {
        'host': 'smtp.sendgrid.net',
        'port': 587,
        'tls': True,
        'user': 'apikey',
    },
    'brevo': {
        'host': 'smtp-relay.brevo.com',
        'port': 587,
        'tls': True,
    },
}

_email_defaults = _EMAIL_PROVIDER_DEFAULTS.get(EMAIL_PROVIDER, _EMAIL_PROVIDER_DEFAULTS['gmail'])

EMAIL_HOST = os.getenv('EMAIL_HOST', '').strip() or os.getenv('SMTP_HOST', '').strip() or _email_defaults['host']
EMAIL_PORT = _to_int(os.getenv('EMAIL_PORT'), _email_defaults['port'])
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', _email_defaults.get('user', '')).strip()
if not EMAIL_HOST_USER:
    EMAIL_HOST_USER = os.getenv('SMTP_USER', '').strip()
if not EMAIL_HOST_USER:
    EMAIL_HOST_USER = os.getenv('SMTP_USERNAME', '').strip()
if not EMAIL_HOST_USER:
    EMAIL_HOST_USER = os.getenv('SMTP_LOGIN', '').strip()
if not EMAIL_HOST_USER:
    EMAIL_HOST_USER = os.getenv('GMAIL_USER', '').strip()
if not EMAIL_HOST_USER:
    EMAIL_HOST_USER = os.getenv('GMAIL_EMAIL', '').strip()
if not EMAIL_HOST_USER and EMAIL_PROVIDER == 'brevo':
    EMAIL_HOST_USER = BREVO_SMTP_LOGIN

EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').strip()
if not EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = os.getenv('SMTP_MAIL', '').strip()
if not EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = os.getenv('SMTP_PASSWORD', '').strip()
if not EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = os.getenv('SMTP_PASS', '').strip()
if not EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = os.getenv('SMTP_KEY', '').strip()
if not EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD', '').strip()
if not EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_APP_PASSWORD', '').strip()
if not EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = os.getenv('GMAIL_APP_PASSWORD', '').strip()
if not EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = os.getenv('GMAIL_PASSWORD', '').strip()
if not EMAIL_HOST_PASSWORD and EMAIL_PROVIDER == 'brevo':
    EMAIL_HOST_PASSWORD = BREVO_SMTP_KEY

# If explicit email password is missing but Brevo credentials are present,
# transparently use Brevo SMTP so OTP delivery can still work.
if (not EMAIL_HOST_PASSWORD) and BREVO_SMTP_LOGIN and BREVO_SMTP_KEY:
    EMAIL_PROVIDER = 'brevo'
    EMAIL_HOST = 'smtp-relay.brevo.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = BREVO_SMTP_LOGIN
    EMAIL_HOST_PASSWORD = BREVO_SMTP_KEY
EMAIL_USE_TLS = _to_bool(os.getenv('EMAIL_USE_TLS'), _email_defaults.get('tls', True))
EMAIL_USE_SSL = _to_bool(os.getenv('EMAIL_USE_SSL'), False)
if EMAIL_USE_SSL:
    EMAIL_USE_TLS = False

EMAIL_TIMEOUT = _to_int(os.getenv('EMAIL_TIMEOUT'), 30)
DEFAULT_FROM_EMAIL = (
    os.getenv('DEFAULT_FROM_EMAIL', '').strip()
    or os.getenv('SENDER_EMAIL', '').strip()
    or EMAIL_HOST_USER
    or 'no-reply@nepstay.com'
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    warnings.warn(
        'SMTP is not fully configured: set EMAIL_HOST_USER and EMAIL_HOST_PASSWORD (or GMAIL_USER and GMAIL_APP_PASSWORD) in .env for OTP emails.',
        RuntimeWarning,
    )

# Used for generating absolute links in email if request object is unavailable.
SITE_BASE_URL = os.getenv('SITE_BASE_URL', 'http://127.0.0.1:8000').strip()