# Generated by Django 6.0.2 on 2026-03-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_created_at_room_availability_room_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelfaqs',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelfeatures',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelgallery',
            name='hotel',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Hotelfaqs',
        ),
        migrations.DeleteModel(
            name='HotelFeatures',
        ),
        migrations.DeleteModel(
            name='HotelGallery',
        ),
    ]
